print("正在创建database.py文件...")
with open("src/models/database.py", "w") as f:
    f.write("from sqlalchemy import create_engine\n")
    f.write("from sqlalchemy.ext.declarative import declarative_base\n")
    f.write("from sqlalchemy.orm import sessionmaker\n")
    f.write("import os\n")
    f.write("\n")
    # 简化的环境变量处理
    f.write("# 数据库配置\n")
    f.write("DB_HOST = '192.168.1.12'\n")
    f.write("DB_USER = 'kis'\n")
    f.write("DB_PASSWORD = 'Kis9090'\n")
    f.write("DB_NAME = 'kis'\n")
    f.write("\n")
    f.write("# MySQL连接URL\n")
    f.write("DATABASE_URL = 'mysql+pymysql://' + DB_USER + ':' + DB_PASSWORD + '@' + DB_HOST + '/' + DB_NAME\n")
    f.write("\n")
    f.write("# 创建数据库引擎\n")
    f.write("engine = create_engine(DATABASE_URL, echo=True)\n")
    f.write("\n")
    f.write("# 创建会话工厂\n")
    f.write("SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)\n")
    f.write("\n")
    f.write("# 创建Base类\n")
    f.write("Base = declarative_base()\n")
    f.write("\n")
    f.write("# 数据库会话实例\n")
    f.write("db_session = SessionLocal()\n")
    f.write("\n")
    f.write("def init_db():\n")
    f.write("    # 简化的初始化\n")
    f.write("    Base.metadata.create_all(bind=engine)\n")
    f.write("\n")
    f.write("def get_db():\n")
    f.write("    db = SessionLocal()\n")
    f.write("    try:\n")
    f.write("        yield db\n")
    f.write("    finally:\n")
    f.write("        db.close()\n")

print("文件创建完成。验证语法...")
try:
    import py_compile
    py_compile.compile("src/models/database.py")
    print("语法检查通过！")
except Exception as e:
    print(f"语法错误: {e}")
